"""CLI for the delivery subcommand."""  # furure todo: rename to "deliver" when fully implemented and taca-ngi-pipieline is deprecated

import click

from taca.delivery import deliver


@click.group()
def delivery():
    """Delivery methods entry point."""
    pass


# Stage data
@delivery.command()
@click.option(
    "-f",
    "--flowcells",
    type=str,
    help="Restrict action to specific flowcell(s). e.g.: 241122_VH00204_464_AAG77JJN5,241120_VH00202_453_AAG76JJM7",
)
@click.option(
    "-s",
    "--samples",
    type=str,
    help="Restrict action to specific sample(s). e.g.: P123_1001,P123_1002 (currently only Illumina and Aviti)",
)
@click.argument("project")
def stage(project, flowcells, samples):
    """Stage a project in DELIVERY and setup DDS delivery project."""
    flowcells_to_stage = flowcells.split(",") if flowcells else None
    samples_to_stage = samples.split(",") if samples else None
    deliver.stage(project, flowcells=flowcells_to_stage, samples=samples_to_stage)


# Upload data
@delivery.command()
@click.option(
    "-s",
    "--stage_dir",
    type=str,
    required=True,
    help="Staged directory to upload",
)
@click.argument("project")
def upload(project, stage_dir):
    """Upload a staged project to DDS."""
    deliver.upload_to_dds(project, stage_dir)


# Release data
@delivery.command()
@click.option(
    "-d",
    "--dds_id",
    type=str,
    required=True,
    help="DDS PID generated by the upload command",
)
@click.argument("project")
def release(project, dds_id):
    """Release a DDS project."""
    deliver.release_dds_project(project, dds_id)
